task: detection

num_classes: 4
class_names: [bus, car, motor, truck]
remap_mscoco_category: True

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox']

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: ./dataset/train
    ann_file: ./dataset/train/_annotations.coco.json
    return_masks: False
    transforms:
      type: Compose
      ops:
        - {type: Resize, size: [640, 640]}
        - {type: ConvertPILImage, dtype: float32, scale: True}
        - {type: ConvertBoxes, fmt: cxcywh, normalize: True}
  shuffle: True
  total_batch_size: 4
  num_workers: 2
  drop_last: True
  collate_fn:
    type: BatchImageCollateFunction

val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: ./dataset/valid
    ann_file: ./dataset/valid/_annotations.coco.json
    return_masks: False
    transforms:
      type: Compose
      ops:
        - {type: Resize, size: [640, 640]}
        - {type: ConvertPILImage, dtype: float32, scale: True}
        - {type: ConvertBoxes, fmt: cxcywh, normalize: True}
  shuffle: False
  total_batch_size: 4
  num_workers: 2
  drop_last: False
  collate_fn:
    type: BatchImageCollateFunction

test_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: ./dataset/test
    ann_file: ./dataset/test/_annotations.coco.json
    return_masks: False
    transforms:
      type: Compose
      ops:
        - {type: Resize, size: [640, 640]}
        - {type: ConvertPILImage, dtype: float32, scale: True}
        - {type: ConvertBoxes, fmt: cxcywh, normalize: True}
  shuffle: False
  total_batch_size: 4
  num_workers: 2
  drop_last: False
  collate_fn:
    type: BatchImageCollateFunction