__include__:
  - ../rtdetrv2_r18vd_120e_coco.yml
  - ../../dataset/custom.yml
  - ../../runtime.yml
  - ./dataloader.yml
  - ./optimizer.yml

output_dir: ./output/label_smoothing/

epoches: 120
remap_mscoco_category: True


model:
  loss:
    type: DETRLoss
    loss_cls:
      type: CrossEntropyLoss
      use_sigmoid: False
      label_smoothing: 0.1
    loss_bbox:
      type: L1Loss
      loss_weight: 7.5
    loss_giou:
      type: GIoULoss
      loss_weight: 3.0

optimizer:
  lr: 0.0001
  weight_decay: 0.0005

lr_scheduler:
  type: MultiStepLR
  milestones: [80]
  gamma: 0.1

use_ema: True
