__include__:
  - ../rtdetrv2_r18vd_120e_coco.yml
  - ../../dataset/custom.yml
  - ../../runtime.yml
  - ./dataloader.yml
  - ./optimizer.yml
  

output_dir: ./output/baseline/

epoches: 120
remap_mscoco_category: True


optimizer:
  type: AdamW
  params:
    - params: '^(?=.*backbone)(?!.*norm).*$'
      lr: 0.00001
    - params: '^(?=.*backbone)(?=.*norm).*$'
      lr: 0.00001
      weight_decay: 0.0
    - params: '^(?=.*(?:encoder|decoder|denoising_class_embed|enc_score_head|enc_bbox_head|dec_score_head|dec_bbox_head))(?=.*norm|bn).*$'
      weight_decay: 0.0
  lr: 0.0001
  betas: [0.9, 0.999]
  weight_decay: 0.0001

lr_scheduler:
  type: MultiStepLR
  milestones: [54]
  gamma: 0.1

use_ema: True
ema:
  type: ModelEMA
  decay: 0.9999
  warmups: 2000

find_unused_parameters: False
sync_bn: False
clip_max_norm: 0.1
# Đay là bản base